# Site settings
title: Infotics
email: adolflow@sindominio.net
description: > # this means to ignore newlines until "baseurl:"
  Transversalidad de la información y las tecnologías
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.infotics.es" # the base hostname & protocol for your site
twitter_username: adolflow
github_username:  flowsta

# Build settings
markdown: kramdown
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

collections:
  my_collection:
    output: true
    permalink: none
